### ISSUE TITLE
Rx2 extension: Issue with incorrect emitting data in the RXSQLite.rx(...) -> RXModelQueriableImpl.queryStreamResults()

### ISSUE THREAD

**Issue by ultraon** [agrosner/DBFlow#1245]
DBFlow Version: 4.0.0-beta7
Issue Kind: Bug

Description: 

The calling CursorResultFlowable.CursorResultObserver.disposable.isDisposed() returns true all the time. For example: https://github.com/Raizlabs/DBFlow/blob/master/dbflow-rx2/src/main/java/com/raizlabs/android/dbflow/rx2/language/CursorResultFlowable.java#L80

Explanation: 
In the CursorResultFlowable.CursorResultObserver the Disposable object is always disposed because it is created by SingleFromCallable when calling RXModelQueriableImpl.queryResults().  The SingleFromCallable.subscribeActual(SingleObserver) calls singleObserver.onSubscribe(EmptyDisposable.INSTANCE) wich is in state disposed befor callin singleObserver.onSuccess(v). In our case the singleObserver is CursorResultObserver (nestet class of the CursorResultFlowable).

see my PR: https://github.com/Raizlabs/DBFlow/pull/1244

Temporary fix for Rx2 extension:
`compile('com.github.ultraon.DBFlow:dbflow-rx2:597b22e4be') {
        exclude group: "com.github.ultraon.DBFlow"
    }`

**Comment by agrosner** [comment]
oy my apologies. this never got addressed. `CursorResult` doesnt exist anymore in 5.0.0-alpha1. The way that transactions work now, you don't need it. `Transaction` return a value, removing need for a `CursorResult` object since now you can just return a `Cursor` from the transaction execution. This method no longer exists.
