### ISSUE TITLE
One To Many Relationship documentation insufficient

### ISSUE THREAD

**Issue by accursedm0** [agrosner/DBFlow#1527]
DBFlow Version: 4.2.4

One To Many [Relationship documentation](https://agrosner.gitbooks.io/dbflow/content/Relationships.html) insufficient: Missing Ant class in example and explanation on how to save models.

Please add the Ant class to make the One To Many example in the docs complete. 
It's essential to get One To Many relationship working. 

Since ModelContainers have been dropped, what do we need do in the Ant class instead of associating the former use of the ForeignKeyContainer? 

Marco got me on the right track with his [post](https://medium.com/@marco_cattaneo/dbflow-4-part-2-relations-and-queries-4b4227e489b2) but he ended up overwriting the Queen.save() in which he "associates" Ants with the Queen. Is it by design that you have to set this connection manually before save() or is it a bug?

I ended up with the following Ant class which seems to work. But is this correct?

```
@Table(database = ColonyDatabase.class)
public class Ant extends BaseModel {

  @PrimaryKey(autoincrement = true)
  long id;

  @Column
  String name;

  @ForeignKey(stubbedRelationship = true)
  Queen queen;

  // need to call this for all ants before saving the queen
  public void setQueen(Queen q) {
    queen = q;
  }
}
```

Thank you very much if you could clarify this.

**Comment by shuxinhuang** [comment]
i face the same issue , need help

**Comment by CaptainRuby** [comment]
+1

**Comment by douglasalipio** [comment]
+1

**Comment by Reaktor17** [comment]
+1

**Comment by 390057892** [comment]
+1 i need help

**Comment by agrosner** [comment]
> Marco got me on the right track with his post but he ended up overwriting the Queen.save() in which he "associates" Ants with the Queen. Is it by design that you have to set this connection manually before save() or is it a bug?

That is a bug from 4.0.2. Was likely fixed by 4.2.4. 

Stubbed relationships are effectively replacement for `ForeignKeyContainer` objects. A full object of `Queen` is fine. 
https://dbflow.gitbook.io/dbflow/usage2/usage/relationships#stubbed-relationships
Let me know if that makes sense. 

> One To Many Relationship documentation insufficient: Missing Ant class in example and explanation on how to save models.

What about it is insufficient? the `Ant` example was dropped and replaced with the `Dog` example in the doc.

**Comment by agrosner** [comment]
And this issue seems mis-titled, rather its about __One To One__ relationships, not _One To Many_. 

> For efficiency reasons we recommend specifying @ForeignKey(stubbedRelationship = true). What this will do is only preset the primary key references into a table object.

> All other fields will not be set. If you need to access the full object, you will have to call load() for Model, or use the ModelAdapter to load the object from the DB.

So the object is there as a field say: 
```
@Table(database = ColonyDatabase.class)
public class Ant extends BaseModel {

  @PrimaryKey(autoincrement = true)
  long id;

  @Column
  String name;

  @ForeignKey(stubbedRelationship = true)
  Queen queen;
}
```

When the table _loads_, it just contains data for the `Queen` primary key fields. The rest are default values (either `null`, 0, etc.). Calling `load()` will query db and overwrite its values with full values. This is more efficient than a full model load, especially in large lists. 

When saving `queen` directly, ensure you load it _before_ you save it, otherwise it'll overwrite the object with default values. When saving from `Ant`, if `@ForeignKey(saveForeignKeyModel = true)`, then it could possibly overwrite its values.

**Comment by agrosner** [comment]
you can shortcut a `load()` if you want to associate a new `queen` with `Ant` by setting the `queen` object, then saving both `Ant` and `Queen`.
