### ISSUE TITLE
CursorWindowAllocationException

### ISSUE THREAD

**Issue by OmarHassan25** [agrosner/DBFlow#1603]
DBFlow Version:
4.2.4

Bug or Feature Request:
After updating to version 4.2.4 I am getting a lot of CursorWindowAllocationException specially for Samsung devices.

Description:
android.database.CursorWindowAllocationException: 
  at android.database.CursorWindow.<init> (CursorWindow.java:108)
  at android.database.AbstractWindowedCursor.clearOrCreateWindow (AbstractWindowedCursor.java:198)
  at android.database.sqlite.SQLiteCursor.clearOrCreateWindow (SQLiteCursor.java:301)
  at android.database.sqlite.SQLiteCursor.fillWindow (SQLiteCursor.java:139)
  at android.database.sqlite.SQLiteCursor.getCount (SQLiteCursor.java:133)
  at android.database.AbstractCursor.moveToPosition (AbstractCursor.java:197)
  at android.database.AbstractCursor.moveToNext (AbstractCursor.java:245)
  at android.arch.b.b.c$1.a (c.java:358)
  at android.arch.b.b.c$1.run (c.java:335)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1112)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)
  at java.lang.Thread.run (Thread.java:818)

**Comment by omar-adel** [comment]
same issue exactly and I don't know if the solution about 

1 - cursor closing and if this how to solve the issue in for example :         sql.querySingle();

there is no cursor in this code , otherwise what am I supposed to do ??

build dbflow library , import it as module and look for cursor operations change what code ????

or as I found here may be problem related to 
2 - maximum size Android SQLite cursor windows can take and that is 2MB
https://stackoverflow.com/questions/11340257/sqlite-android-database-cursor-window-allocation-of-2048-kb-failed

I don't really know the reason for this either 1 or 2 or something else and how to solve this issue ???

**Comment by omar-adel** [comment]
it happen for me in android.database.CursorWindowAllocationException: 
 
  at android.database.CursorWindow.<init> (CursorWindow.java:108)
 
  at android.database.AbstractWindowedCursor.clearOrCreateWindow (AbstractWindowedCursor.java:198)
 
  at android.database.sqlite.SQLiteCursor.clearOrCreateWindow (SQLiteCursor.java:316)
 
  at android.database.sqlite.SQLiteCursor.fillWindow (SQLiteCursor.java:142)
 
  at android.database.sqlite.SQLiteCursor.getCount (SQLiteCursor.java:136)
 
  at android.database.AbstractCursor.moveToPosition (AbstractCursor.java:197)
 
  at android.database.AbstractCursor.moveToFirst (AbstractCursor.java:237)
 
  at android.database.CursorWrapper.moveToFirst (CursorWrapper.java:65)
 
  at com.raizlabs.android.dbflow.sql.queriable.SingleModelLoader.convertToData (SingleModelLoader.java:21)
 
  at com.raizlabs.android.dbflow.sql.queriable.SingleModelLoader.convertToData (SingleModelLoader.java:32)
 
  at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load (ModelLoader.java:72)
 
  at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load (ModelLoader.java:60)
 
  at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load (ModelLoader.java:53)
 
  at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load (ModelLoader.java:36)
 
  at com.raizlabs.android.dbflow.sql.language.BaseModelQueriable.querySingle (BaseModelQueriable.java:69)
 
  at com.raizlabs.android.dbflow.sql.language.Where.querySingle (Where.java:249)

**Comment by agrosner** [comment]
Probably due to unclosed `Cursor` somewhere. If you get time, let me know if you have same issue in 5.0.0-alpha1. What kind of operations on DBFlow were you doing?

**Comment by ReniDelonzek** [comment]
Enfrento o mesmo problema, gostaria de poder contribuir com os logs e o arquivo onde é apontado o problema
**2019-07-03 14:02:16.554 27216-27216/br.com.msk.app.compras E/CursorWindow: Could not allocate CursorWindow '/data/user/0/br.com.msk.app.compras/databases/AppDatabase.db' of size 2097152 due to error -12.
2019-07-03 14:02:16.786 27216-27216/br.com.msk.app.compras E/AndroidRuntime: FATAL EXCEPTION: main
    Process: br.com.msk.app.compras, PID: 27216
    android.database.CursorWindowAllocationException: Cursor window allocation of 2097152 bytes failed. # Open Cursors=1450 (# cursors opened by this proc=1450)

 ....

        at com.raizlabs.android.dbflow.sql.queriable.SingleModelLoader.convertToData(SingleModelLoader.java:25)
        at com.raizlabs.android.dbflow.sql.queriable.SingleModelLoader.convertToData(SingleModelLoader.java:32)
        at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:72)
        at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:60)
        at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:53)
        at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:36)
        at com.raizlabs.android.dbflow.sql.language.BaseModelQueriable.querySingle(BaseModelQueriable.java:69)
        at com.raizlabs.android.dbflow.sql.language.Where.querySingle(Where.java:249)
        at br.com.msk.app.compras.bd.compras.compras2.UnidadeMedidaProduto_Table.loadFromCursor(UnidadeMedidaProduto_Table.java:351)
        at br.com.msk.app.compras.bd.compras.compras2.UnidadeMedidaProduto_Table.loadFromCursor(UnidadeMedidaProduto_Table.java:36)
        at com.raizlabs.android.dbflow.sql.queriable.SingleModelLoader.convertToData(SingleModelLoader.java:25)
        at com.raizlabs.android.dbflow.sql.queriable.SingleModelLoader.convertToData(SingleModelLoader.java:32)
        at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:72)
        at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:60)
        at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:53)
        at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:36)
        at com.raizlabs.android.dbflow.sql.language.BaseModelQueriable.querySingle(BaseModelQueriable.java:69)
        at br.com.msk.app.compras.bd.compras.Produto.getUnidadeMedidaProduto(Produto.kt:59)**

`
/**
 * This is generated code. Please do not modify */
public final class UnidadeMedidaProduto_Table extends ModelAdapter<UnidadeMedidaProduto> {
  /**
   * Primary Key AutoIncrement */
  public static final Property<Integer> id = new Property<Integer>(UnidadeMedidaProduto.class, "id");

  public static final Property<Integer> idServer = new Property<Integer>(UnidadeMedidaProduto.class, "idServer");

  public static final Property<Float> qtdUnidadePrincipal = new Property<Float>(UnidadeMedidaProduto.class, "qtdUnidadePrincipal");

  public static final Property<String> codBar = new Property<String>(UnidadeMedidaProduto.class, "codBar");

  public static final TypeConvertedProperty<Integer, Boolean> deletado = new TypeConvertedProperty<Integer, Boolean>(UnidadeMedidaProduto.class, "deletado", true,
  new TypeConvertedProperty.TypeConverterGetter() {
  @Override
  public TypeConverter getTypeConverter(Class<?> modelClass) {
    UnidadeMedidaProduto_Table adapter = (UnidadeMedidaProduto_Table) FlowManager.getInstanceAdapter(modelClass);
  return adapter.global_typeConverterBooleanConverter;
  }
  });

  public static final Property<Integer> codUsuDelecao = new Property<Integer>(UnidadeMedidaProduto.class, "codUsuDelecao");

  public static final TypeConvertedProperty<Long, Date> dataDelecao = new TypeConvertedProperty<Long, Date>(UnidadeMedidaProduto.class, "dataDelecao", true,
  new TypeConvertedProperty.TypeConverterGetter() {
  @Override
  public TypeConverter getTypeConverter(Class<?> modelClass) {
    UnidadeMedidaProduto_Table adapter = (UnidadeMedidaProduto_Table) FlowManager.getInstanceAdapter(modelClass);
  return adapter.global_typeConverterDateConverter;
  }
  });

  /**
   * Foreign Key */
  public static final Property<Integer> unidadePrincipal_id = new Property<Integer>(UnidadeMedidaProduto.class, "unidadePrincipal_id");

  /**
   * Foreign Key */
  public static final Property<Integer> unidadeMedida_id = new Property<Integer>(UnidadeMedidaProduto.class, "unidadeMedida_id");

  /**
   * Foreign Key */
  public static final Property<Long> produto_id = new Property<Long>(UnidadeMedidaProduto.class, "produto_id");

  /**
   * Foreign Key */
  public static final Property<Integer> marca_id = new Property<Integer>(UnidadeMedidaProduto.class, "marca_id");

  public static final IProperty[] ALL_COLUMN_PROPERTIES = new IProperty[]{id,idServer,qtdUnidadePrincipal,codBar,deletado,codUsuDelecao,dataDelecao,unidadePrincipal_id,unidadeMedida_id,produto_id,marca_id};

  private final DateConverter global_typeConverterDateConverter;

  private final BooleanConverter global_typeConverterBooleanConverter;

  public UnidadeMedidaProduto_Table(DatabaseHolder holder, DatabaseDefinition databaseDefinition) {
    super(databaseDefinition);
    global_typeConverterDateConverter = (DateConverter) holder.getTypeConverterForClass(Date.class);
    global_typeConverterBooleanConverter = (BooleanConverter) holder.getTypeConverterForClass(Boolean.class);
  }

  @Override
  public final Class<UnidadeMedidaProduto> getModelClass() {
    return UnidadeMedidaProduto.class;
  }

  @Override
  public final String getTableName() {
    return "`UnidadeMedidaProduto`";
  }

  @Override
  public final UnidadeMedidaProduto newInstance() {
    return new UnidadeMedidaProduto();
  }

  @Override
  public final Property getProperty(String columnName) {
    columnName = QueryBuilder.quoteIfNeeded(columnName);
    switch ((columnName)) {
      case "`id`":  {
        return id;
      }
      case "`idServer`":  {
        return idServer;
      }
      case "`qtdUnidadePrincipal`":  {
        return qtdUnidadePrincipal;
      }
      case "`codBar`":  {
        return codBar;
      }
      case "`deletado`":  {
        return deletado;
      }
      case "`codUsuDelecao`":  {
        return codUsuDelecao;
      }
      case "`dataDelecao`":  {
        return dataDelecao;
      }
      case "`unidadePrincipal_id`": {
        return unidadePrincipal_id;
      }
      case "`unidadeMedida_id`": {
        return unidadeMedida_id;
      }
      case "`produto_id`": {
        return produto_id;
      }
      case "`marca_id`": {
        return marca_id;
      }
      default: {
        throw new IllegalArgumentException("Invalid column name passed. Ensure you are calling the correct table's column");
      }
    }
  }

  @Override
  public final void updateAutoIncrement(UnidadeMedidaProduto model, Number id) {
    model.setId(id.intValue());
  }

  @Override
  public final Number getAutoIncrementingId(UnidadeMedidaProduto model) {
    return model.getId();
  }

  @Override
  public final String getAutoIncrementingColumnName() {
    return "id";
  }

  @Override
  public final ModelSaver<UnidadeMedidaProduto> createSingleModelSaver() {
    return new AutoIncrementModelSaver<>();
  }

  @Override
  public final IProperty[] getAllColumnProperties() {
    return ALL_COLUMN_PROPERTIES;
  }

  @Override
  public final void bindToInsertValues(ContentValues values, UnidadeMedidaProduto model) {
    values.put("`idServer`", model.getIdServer());
    values.put("`qtdUnidadePrincipal`", model.getQtdUnidadePrincipal());
    values.put("`codBar`", model.getCodBar() != null ? model.getCodBar() : "");
    Integer refdeletado = model.getDeletado() != null ? global_typeConverterBooleanConverter.getDBValue(model.getDeletado()) : null;
    values.put("`deletado`", refdeletado);
    values.put("`codUsuDelecao`", model.getCodUsuDelecao());
    Long refdataDelecao = model.getDataDelecao() != null ? global_typeConverterDateConverter.getDBValue(model.getDataDelecao()) : null;
    values.put("`dataDelecao`", refdataDelecao);
    if (model.getUnidadePrincipal() != null) {
      values.put("`unidadePrincipal_id`", model.getUnidadePrincipal().getId());
    } else {
      values.putNull("`unidadePrincipal_id`");
    }
    if (model.getUnidadeMedida() != null) {
      values.put("`unidadeMedida_id`", model.getUnidadeMedida().getId());
    } else {
      values.putNull("`unidadeMedida_id`");
    }
    if (model.getProduto() != null) {
      values.put("`produto_id`", model.getProduto().getId());
    } else {
      values.putNull("`produto_id`");
    }
    if (model.getMarca() != null) {
      values.put("`marca_id`", model.getMarca().getId());
    } else {
      values.putNull("`marca_id`");
    }
  }

  @Override
  public final void bindToContentValues(ContentValues values, UnidadeMedidaProduto model) {
    values.put("`id`", model.getId());
    bindToInsertValues(values, model);
  }

  @Override
  public final void bindToInsertStatement(DatabaseStatement statement, UnidadeMedidaProduto model,
      int start) {
    statement.bindLong(1 + start, model.getIdServer());
    statement.bindDouble(2 + start, model.getQtdUnidadePrincipal());
    if (model.getCodBar() != null) {
      statement.bindString(3 + start, model.getCodBar());
    } else {
      statement.bindString(3 + start, "");
    }
    Integer refdeletado = model.getDeletado() != null ? global_typeConverterBooleanConverter.getDBValue(model.getDeletado()) : null;
    statement.bindNumberOrNull(4 + start, refdeletado);
    statement.bindNumberOrNull(5 + start, model.getCodUsuDelecao());
    Long refdataDelecao = model.getDataDelecao() != null ? global_typeConverterDateConverter.getDBValue(model.getDataDelecao()) : null;
    statement.bindNumberOrNull(6 + start, refdataDelecao);
    if (model.getUnidadePrincipal() != null) {
      statement.bindLong(7 + start, model.getUnidadePrincipal().getId());
    } else {
      statement.bindNull(7 + start);
    }
    if (model.getUnidadeMedida() != null) {
      statement.bindLong(8 + start, model.getUnidadeMedida().getId());
    } else {
      statement.bindNull(8 + start);
    }
    if (model.getProduto() != null) {
      statement.bindLong(9 + start, model.getProduto().getId());
    } else {
      statement.bindNull(9 + start);
    }
    if (model.getMarca() != null) {
      statement.bindLong(10 + start, model.getMarca().getId());
    } else {
      statement.bindNull(10 + start);
    }
  }

  @Override
  public final void bindToStatement(DatabaseStatement statement, UnidadeMedidaProduto model) {
    int start = 0;
    statement.bindLong(1 + start, model.getId());
    bindToInsertStatement(statement, model, 1);
  }

  @Override
  public final void bindToUpdateStatement(DatabaseStatement statement, UnidadeMedidaProduto model) {
    statement.bindLong(1, model.getId());
    statement.bindLong(2, model.getIdServer());
    statement.bindDouble(3, model.getQtdUnidadePrincipal());
    if (model.getCodBar() != null) {
      statement.bindString(4, model.getCodBar());
    } else {
      statement.bindString(4, "");
    }
    Integer refdeletado = model.getDeletado() != null ? global_typeConverterBooleanConverter.getDBValue(model.getDeletado()) : null;
    statement.bindNumberOrNull(5, refdeletado);
    statement.bindNumberOrNull(6, model.getCodUsuDelecao());
    Long refdataDelecao = model.getDataDelecao() != null ? global_typeConverterDateConverter.getDBValue(model.getDataDelecao()) : null;
    statement.bindNumberOrNull(7, refdataDelecao);
    if (model.getUnidadePrincipal() != null) {
      statement.bindLong(8, model.getUnidadePrincipal().getId());
    } else {
      statement.bindNull(8);
    }
    if (model.getUnidadeMedida() != null) {
      statement.bindLong(9, model.getUnidadeMedida().getId());
    } else {
      statement.bindNull(9);
    }
    if (model.getProduto() != null) {
      statement.bindLong(10, model.getProduto().getId());
    } else {
      statement.bindNull(10);
    }
    if (model.getMarca() != null) {
      statement.bindLong(11, model.getMarca().getId());
    } else {
      statement.bindNull(11);
    }
    statement.bindLong(12, model.getId());
  }

  @Override
  public final void bindToDeleteStatement(DatabaseStatement statement, UnidadeMedidaProduto model) {
    statement.bindLong(1, model.getId());
  }

  @Override
  public final String getInsertStatementQuery() {
    return "INSERT INTO `UnidadeMedidaProduto`(`idServer`,`qtdUnidadePrincipal`,`codBar`,`deletado`,`codUsuDelecao`,`dataDelecao`,`unidadePrincipal_id`,`unidadeMedida_id`,`produto_id`,`marca_id`) VALUES (?,?,?,?,?,?,?,?,?,?)";
  }

  @Override
  public final String getCompiledStatementQuery() {
    return "INSERT INTO `UnidadeMedidaProduto`(`id`,`idServer`,`qtdUnidadePrincipal`,`codBar`,`deletado`,`codUsuDelecao`,`dataDelecao`,`unidadePrincipal_id`,`unidadeMedida_id`,`produto_id`,`marca_id`) VALUES (?,?,?,?,?,?,?,?,?,?,?)";
  }

  @Override
  public final String getUpdateStatementQuery() {
    return "UPDATE `UnidadeMedidaProduto` SET `id`=?,`idServer`=?,`qtdUnidadePrincipal`=?,`codBar`=?,`deletado`=?,`codUsuDelecao`=?,`dataDelecao`=?,`unidadePrincipal_id`=?,`unidadeMedida_id`=?,`produto_id`=?,`marca_id`=? WHERE `id`=?";
  }

  @Override
  public final String getDeleteStatementQuery() {
    return "DELETE FROM `UnidadeMedidaProduto` WHERE `id`=?";
  }

  @Override
  public final String getCreationQuery() {
    return "CREATE TABLE IF NOT EXISTS `UnidadeMedidaProduto`(`id` INTEGER PRIMARY KEY AUTOINCREMENT, `idServer` INTEGER, `qtdUnidadePrincipal` REAL, `codBar` TEXT, `deletado` INTEGER, `codUsuDelecao` INTEGER, `dataDelecao` INTEGER, `unidadePrincipal_id` INTEGER, `unidadeMedida_id` INTEGER, `produto_id` INTEGER, `marca_id` INTEGER"+ ", FOREIGN KEY(`unidadePrincipal_id`) REFERENCES " + com.raizlabs.android.dbflow.config.FlowManager.getTableName(br.com.msk.app.compras.bd.compras.compras2.UnidadeMedidaProduto.class) + "(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION"+ ", FOREIGN KEY(`unidadeMedida_id`) REFERENCES " + com.raizlabs.android.dbflow.config.FlowManager.getTableName(br.com.msk.app.compras.bd.compras.compras2.UnidadeMedida.class) + "(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION"+ ", FOREIGN KEY(`produto_id`) REFERENCES " + com.raizlabs.android.dbflow.config.FlowManager.getTableName(br.com.msk.app.compras.bd.compras.Produto.class) + "(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION"+ ", FOREIGN KEY(`marca_id`) REFERENCES " + com.raizlabs.android.dbflow.config.FlowManager.getTableName(br.com.msk.app.compras.bd.compras.compras2.Marca.class) + "(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION" + ");";
  }

  @Override
  public final void loadFromCursor(FlowCursor cursor, UnidadeMedidaProduto model) {
    model.setId(cursor.getIntOrDefault("id"));
    model.setIdServer(cursor.getIntOrDefault("idServer"));
    model.setQtdUnidadePrincipal(cursor.getFloatOrDefault("qtdUnidadePrincipal"));
    model.setCodBar(cursor.getStringOrDefault("codBar", ""));
    int index_deletado = cursor.getColumnIndex("deletado");
    if (index_deletado != -1 && !cursor.isNull(index_deletado)) {
      model.setDeletado(global_typeConverterBooleanConverter.getModelValue(cursor.getInt(index_deletado)));
    } else {
      model.setDeletado(global_typeConverterBooleanConverter.getModelValue(null));
    }
    model.setCodUsuDelecao(cursor.getIntOrDefault("codUsuDelecao", null));
    int index_dataDelecao = cursor.getColumnIndex("dataDelecao");
    if (index_dataDelecao != -1 && !cursor.isNull(index_dataDelecao)) {
      model.setDataDelecao(global_typeConverterDateConverter.getModelValue(cursor.getLong(index_dataDelecao)));
    } else {
      model.setDataDelecao(global_typeConverterDateConverter.getModelValue(null));
    }
    int index_unidadePrincipal_id_UnidadeMedidaProduto_Table = cursor.getColumnIndex("unidadePrincipal_id");
    if (index_unidadePrincipal_id_UnidadeMedidaProduto_Table != -1 && !cursor.isNull(index_unidadePrincipal_id_UnidadeMedidaProduto_Table)) {
      model.setUnidadePrincipal(com.raizlabs.android.dbflow.sql.language.SQLite.select().from(br.com.msk.app.compras.bd.compras.compras2.UnidadeMedidaProduto.class).where()
          .and(br.com.msk.app.compras.bd.compras.compras2.UnidadeMedidaProduto_Table.id.eq(cursor.getInt(index_unidadePrincipal_id_UnidadeMedidaProduto_Table)))
          .querySingle());
    } else {
      model.setUnidadePrincipal(null);
    }
    int index_unidadeMedida_id_UnidadeMedida_Table = cursor.getColumnIndex("unidadeMedida_id");
    if (index_unidadeMedida_id_UnidadeMedida_Table != -1 && !cursor.isNull(index_unidadeMedida_id_UnidadeMedida_Table)) {
      model.setUnidadeMedida(com.raizlabs.android.dbflow.sql.language.SQLite.select().from(br.com.msk.app.compras.bd.compras.compras2.UnidadeMedida.class).where()
          .and(br.com.msk.app.compras.bd.compras.compras2.UnidadeMedida_Table.id.eq(cursor.getInt(index_unidadeMedida_id_UnidadeMedida_Table)))
          .querySingle());
    } else {
      model.setUnidadeMedida(null);
    }
    int index_produto_id_Produto_Table = cursor.getColumnIndex("produto_id");
    if (index_produto_id_Produto_Table != -1 && !cursor.isNull(index_produto_id_Produto_Table)) {
      model.setProduto(com.raizlabs.android.dbflow.sql.language.SQLite.select().from(br.com.msk.app.compras.bd.compras.Produto.class).where()
          .and(br.com.msk.app.compras.bd.compras.Produto_Table.id.eq(cursor.getLong(index_produto_id_Produto_Table)))
          .querySingle());
    } else {
      model.setProduto(null);
    }
    int index_marca_id_Marca_Table = cursor.getColumnIndex("marca_id");
    if (index_marca_id_Marca_Table != -1 && !cursor.isNull(index_marca_id_Marca_Table)) {
      model.setMarca(com.raizlabs.android.dbflow.sql.language.SQLite.select().from(br.com.msk.app.compras.bd.compras.compras2.Marca.class).where()
          .and(br.com.msk.app.compras.bd.compras.compras2.Marca_Table.id.eq(cursor.getInt(index_marca_id_Marca_Table)))
          .querySingle());
    } else {
      model.setMarca(null);
    }
  }

  @Override
  public final boolean exists(UnidadeMedidaProduto model, DatabaseWrapper wrapper) {
    return model.getId() > 0
    && SQLite.selectCountOf()
    .from(UnidadeMedidaProduto.class)
    .where(getPrimaryConditionClause(model))
    .hasData(wrapper);
  }

  @Override
  public final OperatorGroup getPrimaryConditionClause(UnidadeMedidaProduto model) {
    OperatorGroup clause = OperatorGroup.clause();
    clause.and(id.eq(model.getId()));
    return clause;
  }
}
`
