### ISSUE TITLE
Check if column exists

### ISSUE THREAD

**Issue by felipezf** [agrosner/DBFlow#1632]
DBFlow Version: 4.2.4

Bug or Feature Request: Check if column exists on migration

Description: Due to issues with migrations, I have some users that are having issues with database Migration. Now, I need to release a update which checks if column exists or not, and if not exist, it should create this column. How can I do this using the migration?

**Comment by agrosner** [comment]
well this is a SQLite question. We do this in the `AlterTableMigration` as follows: 
```kotlin
if (internalColumnDefinitions.isNotEmpty()) {
            (select from table limit 0).cursor(database)?.use { cursor ->
                sql = "$sql$tableName"
                for (i in internalColumnDefinitions.indices) {
                    val columnDefinition = internalColumnDefinitions[i]
                    val columnName = columnNames[i].stripQuotes()
                    if (cursor.getColumnIndex(columnName) == -1) {
                        database.execSQL("$sql ADD COLUMN $columnDefinition")
                    }
                }
            }
        }
```

**Comment by agrosner** [comment]
since SQLite does not support `IF NOT EXISTS` on an alter migration, we have to query existing row to see if its retrieved in a `Cursor`.

**Comment by felipezf** [comment]
@agrosner Thanks!

**Comment by eschoenawa** [comment]
Since the `AlterTableMigration` doesn't support overriding the `migrate`-method, is there some way I can get the DatabaseWrapper in `onPreMigrate`, in order to use the code shown above by @agrosner ? Since I want to use the logic to only add a column when it doesn't exist and adding that column is done in `onPreMigrate`.

Or is the only solution to write my own version of the `AlterTableMigration` so I can put the check into the `migrate` function?

**Comment by peterchaula** [comment]
Another solution -- albeit a dirty one -- would be to run each migration in a try...catch block. I have not tried but I'm sure it would work..


try
  add_column 'abc'
catch:

try
  add_column 'abd'
catch:
