### ISSUE TITLE
Annotation processors must be explicitly declared now.

### ISSUE THREAD

**Issue by munl** [agrosner/DBFlow#1660]
# ISSUE\_TEMPLATE

DBFlow Version: 3.1.1

Bug or Feature Request: Bug

Description:
I'm trying to build my app but I'm getting the following error:

Annotation processors must be explicitly declared now.  The following dependencies on the compile classpath are found to contain annotation processor.  Please add them to the annotationProcessor configuration.
- dbflow-processor-3.1.1.jar (com.github.Raizlabs.DBFlow.dbflow-core:dbflow-processor:3.1.1)
- dbflow-processor-3.1.1.jar (com.github.Raizlabs.DBFlow.dbflow:dbflow-processor:3.1.1)

Alternatively, set android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath = true to continue with previous behavior.  Note that this option is deprecated and will be removed in the future.

**Comment by aguitto** [comment]
The issue is that Gradle is downloading 2 versione of dbflow-core lib

Download https://jitpack.io/com/github/Raizlabs/DBFlow/dbflow-core/3.1.1/dbflow-core-3.1.1.jar
Download https://jitpack.io/com/github/Raizlabs/DBFlow/dbflow-core/dbflow-core/3.1.1/dbflow-core-3.1.1.jar

The first one has the of 22 bytes instead of the second one which have the size of 44 Kb.
The second is the right one but i think there are some problems in dependecies path.

**Comment by agrosner** [comment]
newer versions of the library are supported. did you try using a newer version?
